### PR TITLE
Authenticate

### PR DESCRIPTION
**Pull request by GabrielGramlich**
@4LineTime @Nelwell @KhadarRashid 
Added the authentication functions. Creating a salt improves security of the credentials. Hashing the password allows it to be stored securely. Matching function is pretty self-explanatory.

### CODE REVIEW

**Comment by Nelwell** [comment]
Tried to run this module on a Windows PC and got this error: "ImportError: The crypt module is not supported on Windows".

Did a little Googling and found out crypt module is Linux-only? May need to switch to a different module if that's the case here. Looking at the thread some more, I see a promising suggestion to use passlib instead.  I'm not familiar enough with this to get it work after about 20 min of trying it out but maybe take a look at it yourself?  As-is, it won't run on Windows from what I can see though, and presumably Mac if it's Linux only without running it under a Linux environment. 

Take at glance at https://stackoverflow.com/questions/19877867/using-the-crypt-module-in-windows and see if you can get passlib working?  Here is the code-snippet from the poster's suggestion (about 3-4 postings deep):

from passlib.hash import sha512_crypt as sha512

sha512_passwd = sha512.encrypt(passwd, rounds=5000, implicit_rounds=True)

Otherwise, I feel like a lot of the code makes sense and looks clean/proper to me.

**Comment by GabrielGramlich** [comment]
@Nelwell Yeah, there's other modules we can use. I would prefer the whole world uses Linux, but that's my own bias. Will find another method and update the branch.

**Comment by GabrielGramlich** [comment]
Point of clarification, the crypt module is for the creation of a salt, not to hash the password, like passlib, but I'm looking for an alternate salt generator.

**Comment by GabrielGramlich** [comment]
Updated with bcrypt, a module usable with Windows.

**Comment by Nelwell** [comment]
Looked over and made a few adjustments to spacing between first method and import statements to make "proper" based on pycharm linting suggestions, finished what appeared to be an incomplete comment about the bcrypt module and made its formatting consistent with other comments in the module.  Also updated requirements.txt to include bcrypt module.  I have no issues with the present state of the code and it seems to run fine on my end.  I would make the merge but wanted to allow someone else to check over my minor tweaks before merging. So feel free to merge after checking over, thanks.

**Pull request merged**
